a = ["Boulangerie campaillette dijon.jpg",
"Hôtel de Bretagne dijon.jpg",
"Porte Stanislas Nancy.jpg",
"Arc héré Nancy.jpg",
"Arche dijon.jpg",
"Banque LCL Tulle.jpg",
"Brivezac sur dordogne lieu dit Peyriget.jpg",
"Caserne Paris 1.jpg",
"Caserne Paris 2.jpg",
"Cathédrale nord Clermont-Ferrand.jpg",
"Cathédrale sud Clermont-Ferrand.jpg",
"Cathédrale Tulle.jpg",
"Cathédrale de Strasbourg.jpg",
"Cathédrale notre dame de l'Annonciation Nancy.jpg",
"Collège Simone Veil, Cheneraille.jpg",
"Cimetière Vert-Saint-Denis.jpg",
"Cimetière de Pont à Mousson.jpg",
"Cimetière de Rougnat.jpg",
"Croisement rue du cailloux Cesson.jpg",
"Eglise Damelevieres.jpg",
"Eglise Saint Julien Tours.jpg",
"Eglise Voinsles.jpg",
"Abbaye d'Aubazine.jpg",
"Eglise d'Egleton.jpg",
"Eglise de Jard-Sur-Mer.jpg",
"Eglise de Jarnage.jpg",
"Eglise de Maron.jpg",
"Eglise de la Savonnières.jpg",
"Eglise lac Xonrupt-Longemer.jpg",
"Chapelle du Sacré-Cœur Les Sables d'Olonnes.jpg",
"Ensemble scolaire Foucault Nancy.jpg",
"Espace culturel charle boizard Puy-l'évêque.jpg",
"Faculté de droits Nancy.jpg",
"Fontaine des bosquets Luneville.jpg",
"Gare varangéville.jpg",
"Hôtel Dieu Paris.jpg",
"Hôtel de ville Luneville.jpg",
"Institut de Paris 1.jpg",
"Institut de Paris 2.jpg",
"L'église de saint Pierre ès liens, Saint Pierre Cherignat.jpg",
"Mairie Nancy.jpg",
"Mairie de Boussac.jpg",
"Mairie de Brive-la-Gaillarde.jpg",
"Monument aux morts Col de Laléger.jpg",
"Opéra de Nancy.jpg",
"Palais des états Dijon.jpg",
"Pont de Maron.jpg",
"Pont de l'Indre, Azay le rideau.jpg",
"Port Saint Tropez.jpg",
"Porte Saint-Georges Nancy.jpg",
"Porte de la Craffe Nancy.jpg",
"Place de la Poste de Pionnat.jpg",
"Puit Gassin.jpg",
"Restaurant Floréal Luneville.jpg",
"Route de haraucourt.jpg",
"Rue de l'hôtel de Ville Merlines.jpg",
"Saint Germain les belles.jpg",
"Square Darcy Dijon.jpg",
"Stalingrad Paris.jpg",
"Temple protestant Nancy.jpg",
"Théâtre Strasbourg.jpg",
"Théâtre de Tulle.jpg",
"Tribunal judiciaire Tulle.jpg",
"Arcade saint epvre Nancy.jpg",
"gare de Tulle.jpg",
"Saint-Pardoux-les-Cards lieu dit Ecurat.jpg",
"lycée Chaptal Paris.jpg",
"musée magnin dijon.jpg",
"notre dame de la route Fontanières.jpg",
"pont saint julien au bois le pied de lune.jpg",
"porte de la Villette 1.jpg",
"porte de la Villette 2.jpg",
"rue Georges Toussaint.jpg",
"vieux bâtiment Cesson.jpg",
"Église Rosières.jpg",
"Eglise Ducal Nancy.jpg",
"Caillou, au croisement de la départementale 941 avant St Amand Jartoudeix lieu dit Le Nouhaud.jpg",
"Eglise de Bourganeuf.jpg",
"Eglise Savigny-le-temple.jpg",
"Mur d'une maison, Savigny-le-temple.jpg",
"Mairie annexe Villers-sur-Mer.jpg",
"Poste Villers-sur-Mer.jpg",
"Eglise Saint-Martin Villers-sur-Mer.jpg",
"Eglise Trouville-sur-Mer.jpg",
"Eglise Villerville.jpg",
"Chapelle aux Lierres Cricqueboeuf.jpg",
"La lieutenance Honfleur.jpg",
"Vieux bassin Honfleur.jpg",
"Port Honfleur, grande roue.jpg",
"Eglise Sainte-Catherine Honfleur.jpg",
"Eglise Saint-Leonard Honfleur.jpg",
"Eglise Saint Michel Cabourg.jpg",
"Eglise Saint-Jacques Reims.jpg",
"Rue Thiers Reims.jpg",
"Boulevard Foch Reims.jpg",
"Boulevard Jules Cesar Reims.jpg",
"Mairie Marcillac la Croisille.jpg",
"Eglise Luneville.jpg",
"Porte Sainte-Catherine Nancy.jpg",
"Eglise Laneuveville-devant-Nancy.jpg",
"Église Notre-Dame-de-Bonsecours Nancy.jpg",
"Eglise de Saint-Léonard-de-Noblat.jpg",
"Parc Buttes-Chaumont 1 Paris.jpg",
"Parc Buttes-Chaumont 2 Paris.jpg",
"Parc Buttes-Chaumont 3 Paris.jpg",
"Cimetière de Cubjac-Auvezere-Val D'ans.jpg",
"Maison Cubjac-Auvezere-Val D'ans.jpg",
"Eglise Gout-Rossignol.jpg",
"Maison Savignac-les-Églises.jpg",
"Entrée de ville Lorey.jpg",
"Mairie Saffais.jpg",
"Église Saint-Mard.jpg",
"École de la Providence Bayon.jpg",
"Maison Bayon.jpg",
"Eglise Roville-Devant-Bayon.jpg",
"Cimetière Crantenoy.jpg",
"Pont du Madon, Haroué.jpg",
"Mairie Tantonville.jpg",
"Eglise Praye.jpg",
"Mairie Badonviller.jpg",
"Musée-Atelier Céramique Badonviller.jpg",
"Cimetière Badonviller.jpg",
"Droguerie Badonviller.jpg",
"Logement social Badonviller.jpg",
"Église Fenneviller.jpg",
"Mairie Pexonne.jpg",
"Mairie 10eme arrondissement Paris.jpg",
"Porte saint Martin Paris.jpg",
"Place à L'hospice Uzerche.jpg",
"Presbytère Uzerche.jpg",
"Mairie Brunoy.jpg",
"Maison Brunoy.jpg",
"Gare de Cesson.jpg",
"Borne fontaine au croisement rue Bouret et rue Armand carrel Paris.jpg",
"Creche rue Armand carrel Paris.jpg",
"Croisement rue Armand Carrel et rue de meaux Paris.jpg",
"Croisement rue faubourg saint Martin et rue Eugène Varlin Paris.jpg",
"Gare de l'est.jpg",
"Parc Buttes-Chaumont 4 Paris.jpg",
"Parc Buttes-Chaumont 5 Paris.jpg",
"Parc Buttes-Chaumont 6 Paris.jpg",
"Place Armand Carrel.jpg",
"Rue du Rhin Paris.jpg",
"Rue de meaux, station Laumière Paris.jpg",
"Stalingrad 2 Paris.jpg",
"Pont de Bercy.jpg",
"Pont de Tolbiac.jpg",
"Quai de Bercy.jpg",
"Quai de la râpée.jpg",
"Tunnel proudhon.jpg",
"Avenue du Président Kennedy, kenclub Paris.jpg",
"Croisement Avenue du Président Kennedy, rue d'Ankara Paris.jpg",
"Croisement Boulevard de Belleville, Rue D'Oberkampf Paris.jpg",
"Eglise Gimel-les-Cascades.jpg",
"Eglise Vert-Saint-Denis.jpg",
"Gare d'avenue du président Kennedy Paris.jpg",
"LCL croisement rue Daniel Stern, boulevard de grenelles Paris.jpg",
"Le Reverdi Cesson.jpg",
"Pont d'Inéa Paris.jpg",
"Port Debilly, Pont d'Inéa Paris.jpg",
"Poste croisement rue du théâtre, rue de Lourmel Paris.jpg",
"Rond point Vert-Saint-Denis.jpg",
"Rue de Lourmel École Saint Elizabeth Paris.jpg",
"Rue de Lourmel, arrêt 42 Charles Michels Paris.jpg",
"Rue Émile Zola Restaurant l'épopée Paris.jpg",
"Sortie parc de Belleville rue Julien Lacroix Paris.jpg",
"Gare Melun.jpg",
"Château de Fontainebleau.jpg",
"Église Saint-Louis - Fontainebleau.jpg",
"Le grand canal bridge - Fontainebleau.jpg",
"Rue Paul Séramy - Fontainebleau.jpg",
"La Poste - Fontainbleau.jpg",
"Passage à niveau - La Grande-Paroisse.jpg",
"Eglise Saint-Germain-de-Paris - La Grande-Paroisse.jpg",
"Ecole Primaire Clovis Moriot - La Grande-Paroisse.jpg",
"Rue de la Garenne - La Grande-Paroisse.jpg",
"Rue Haute - La Grande-Paroisse.jpg",
"Arc de Triomphe du Carrousel Paris.jpg",
"Chapelle Villemoneix.jpg",
"Cimetière Seine-Port.jpg",
"Croisement rue Ernest Legouvé, Route de Nandy Seine-Port.jpg",
"Eglise Seine-Port.jpg",
"Entrée Chicane, Seine-Port.jpg",
"Rapid'Market Seine-Port.jpg",
"Nouveau Quartier Seine-Port.jpg",
"Le Balory Seine-Port.jpg",
"Pont Évry.jpg",
"Jardin Lecoq Clermont-Ferrand.jpg",
"Paris 10eme, sapeur pompier.jpg",
"Olivier Et Co - Levallois-Perret.jpg",
"Église Saint-Pierre-de-Montrouge - Paris.jpg",
"Palais d'Orléans - Paris.jpg",
"Jardin de l'Observatoire de Paris.jpg",
"16b Av. René Coty - Paris.jpg",
"Lirairie petit Limoges.jpg",
"Pouilly-le-Fort.jpg",
"Eglise - Réau.jpg",
"Ecole - Réau.jpg",
"Mairie - Réau.jpg",
"Rue Sophie Germain - Paris.jpg",
"19 bis Av. du Général Leclerc - Paris.jpg",
"Hotel de Police 14e - Paris.jpg",
"Maison rue de Paris - Cesson.jpg",
"Pont de Tolbiac 2.jpg",
"Bouvard Diderot Paris.jpg",
"Paris Gare de Lyon.jpg",
"Rue de l'église de Crisenoy.jpg",
"Eglise Saint-Maurice - Blandy.jpg",
"Rue Vauchevres - Blandy.jpg",
"Pont Paillard - Blandy.jpg",
"Sous le pont de la gare de Melun.jpg",
"Chapelle du Puy Saint Clair, Tulle.jpg",
"Croisement boulevard Diderot, rue de Bercy Paris.jpg",
"Gare de Lyon, rue de Lyon et Bd Diderot, Paris.jpg",
"Chateau d'eau rue joffre Colmar.jpg",
"Église des Dominicains Colmar.jpg",
"EM Lyon business school Paris.jpg",
"Chateau d'eau Boutigny-sur-Essonne.jpg",
"La Poste Chevry-Cossigny.jpg",
"Paroisse de Chevry-Cossigny.jpg",
"Eglise de Chevry-Cossigny.jpg"]

import os

i=0

for obj in a:
    nom = str(i)+".jpg"
    try:
        os.rename(obj,nom)
    except:
        print("aie")
    i+=1